version: "3.8"

services:

  #################################
  # Transaction: The Transaction microservice
  #################################
  transaction:
    build:
      dockerfile: Dockerfile
      context: './services/transaction'
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/transaction
    ports:
      - "5100:5000"

  #################################
  # Customer: The Customer microservice
  #################################
  customer:
    build:
      dockerfile: Dockerfile
      context: './services/customer'
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/customer
    ports:
      - "5001:5000"

  #################################
  # Roundup: The Roundup microservice
  #################################
  roundup:
    build:
      dockerfile: Dockerfile
      context: './services/roundup'
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/roundup
    ports:
      - "5002:5000"

